from random import *
num = randint(4, 28)
print("오프라인 스터디 모임 날짜는 매월 "+str(num)+" 일로 선정되었습니다.")
num = randint(4, 28)
print("오프라인 스터디 모임 날짜는 매월 "+str(num)+" 일로 선정되었습니다.")
num = randint(4, 28)
print("오프라인 스터디 모임 날짜는 매월 "+str(num)+" 일로 선정되었습니다.")
num = randint(4, 28)
print("오프라인 스터디 모임 날짜는 매월 "+str(num)+" 일로 선정되었습니다.")
num = randint(4, 28)
print("오프라인 스터디 모임 날짜는 매월 "+str(num)+" 일로 선정되었습니다.")
